#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  clients:
    type: local
    number: 1
  rounds:
  - label: init
    txDuration:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: benchmarks/samples/fabric/marbles/init.js
  - label: init
    txDuration:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    callback: benchmarks/samples/fabric/marbles/init.js
  - label: init
    txDuration:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    callback: benchmarks/samples/fabric/marbles/init.js
  - label: init
    txDuration:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 40
    callback: benchmarks/samples/fabric/marbles/init.js
  - label: init
    txDuration:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmarks/samples/fabric/marbles/init.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: benchmarks/samples/fabric/marbles/query.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    callback: benchmarks/samples/fabric/marbles/query.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    callback: benchmarks/samples/fabric/marbles/query.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 40
    callback: benchmarks/samples/fabric/marbles/query.js
  - label: query
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    callback: benchmarks/samples/fabric/marbles/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1

